version: '3.1'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: my_db_name #Database name
      MYSQL_USER: user # change username
      MYSQL_PASSWORD: secret # change password
      MYSQL_ROOT_PASSWORD: secret # change root password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

volumes:
  mysql-data:

###
# http://lcoalhost:3306
###