# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password # change password for postgresql

# A gui workbench for postgres in browers
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080


###
# http://localhost:5432
###